using System;
using System.Collections.Generic;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using TOP.UI.WPF.Data.TOP_Page_Data;

namespace TOP.UI.WPF.UI.Pages
{
    /// <summary>
    /// Interaction logic for TOP_Page.xaml
    /// </summary>
    public partial class TOP_Page : UserControl
    {
        readonly TOP_Page_Methods top_Page_Methods = new TOP_Page_Methods();
        public TOP_Page()
        {
            InitializeComponent();
            top_Page_Methods.LoadDetails(AcceptItem, EditItem, DeleteItem, TOPsDataGrid, cboTeacherAdd,
               cboVocationQualificationUnitAdd);
        }

        private void TOPsDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            top_Page_Methods.TOPsDataGridColumns(TOPsDataGrid);
        }

        private void SeeDetailsItem_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.ShowDetailsOfTOP(txtCompanyAdd, txtAddressAdd, cboTeacherAdd, cboVocationQualificationUnitAdd, txtPhoneAdd,
                txtEmailAdd, txtInfoAdd, TOPsDataGrid, TOP_Panel, btnOk);
        }

        private void ReserveItem_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.ReserveTOP(TOPsDataGrid);
        }

        private void AcceptItem_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.AcceptTOP(TOPsDataGrid);
        }

        private void EditItem_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.TOP_Panel_Action(TOP_Panel, 300, "edit", txtCompanyAdd, txtAddressAdd, cboTeacherAdd, cboVocationQualificationUnitAdd, txtPhoneAdd,
                txtEmailAdd, txtInfoAdd, TOPsDataGrid, btnOk);
        }

        private void DeleteItem_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.DeleteTOP(TOPsDataGrid);
        }

        private void btnNewTOP_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.TOP_Panel_Action(TOP_Panel, 300, btnNewTOP.Tag.ToString(), txtCompanyAdd, txtAddressAdd, cboTeacherAdd, cboVocationQualificationUnitAdd, txtPhoneAdd,
                txtEmailAdd, txtInfoAdd, TOPsDataGrid, btnOk);
        }

        private void btnClosePanel_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.TOP_Panel_Action(TOP_Panel, 0, "", txtCompanyAdd, txtAddressAdd, cboTeacherAdd, cboVocationQualificationUnitAdd, txtPhoneAdd,
                txtEmailAdd, txtInfoAdd, TOPsDataGrid, btnOk);
        }

        private void btnOk_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.SaveTOP(txtCompanyAdd, txtAddressAdd, cboTeacherAdd, cboVocationQualificationUnitAdd, txtPhoneAdd,
                txtEmailAdd, txtInfoAdd, TOPsDataGrid, TOP_Panel, btnOk);
        }

        private void btnSearch_Click(object sender, RoutedEventArgs e)
        {
            top_Page_Methods.GetTOPs(TOPsDataGrid);
        }
    }
}
